# Generated by Django 4.1 on 2023-01-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('midfield_points', models.IntegerField()),
                ('forward_points', models.IntegerField()),
                ('defender_points', models.IntegerField()),
                ('keeper_points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Midfield', 'Midfield'), ('Forward', 'Forward'), ('Defender', 'Defender'), ('Keeper', 'Keeper')], max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.round')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.leaguerule')),
            ],
        ),
    ]
