# Generated by Django 4.1 on 2023-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpoints",
            name="points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
