# Generated by Django 4.1 on 2023-02-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0002_playerpoints_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguerule",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="league",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fantasy.league",
                unique=True,
            ),
        ),
    ]
