# Generated by Django 4.1 on 2023-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0008_league_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguerule",
            name="initial_forms",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
