# Generated by Django 4.1 on 2023-05-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0009_leaguerule_initial_forms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerpoints",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fantasy.leaguerule",
            ),
        ),
    ]
