# Generated by Django 4.1 on 2023-05-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0012_rename_home_score_round_opposition_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguerule",
            name="calculated_from_score",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="playerpoints",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fantasy.leaguerule"
            ),
        ),
    ]
