# Generated by Django 4.1 on 2023-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0013_leaguerule_calculated_from_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguerule",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
