# Generated by Django 4.1 on 2023-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0014_alter_leaguerule_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguerule",
            name="autofill",
            field=models.BooleanField(default=False),
        ),
    ]
